### ISSUE TITLE
warnings: False positives with `LostWaker` warning

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/console#149]
Currently, the `LostWaker` warning seems to often display false positives. These seem to occur when a task has a single waker clone, is woken by value (dropping the waker), and yields _after_ having been woken. This seems to occur the most frequently when a task self-wakes (and that _may_ be the only instance where this occurs?).

It would be nice to fix this --- the warning _should_ only be shown when a task definitely won't be woken again. However, I'm not immediately sure how we would determine this.

One potential solution is that the false-positives seem to be pretty transient. They flicker in and out of existence rapidly. We could potentially just only display the lint if the task has _remained_ in the 0-waker state for a long time.

**Comment by seanmonstar** [comment]
Maybe we can check if `last_wake` is after `last_poll_started`, and if so we can assume it will be polled again?

**Comment by Milo123459** [comment]
Sadly this doesn't fix the issue I was coming across. I still get a lost waker

**Comment by hawkw** [comment]
Hmm, that's surprising!

**Comment by hawkw** [comment]
On the latest `main` branch I see a ton of (apparent) false positives, just running the demo app like
```shell
$ cargo run --example app &
$ cargo run
```
![image](https://user-images.githubusercontent.com/2796466/134218050-1295012a-88ea-4845-a0a1-049cf13fe0f8.png)

I'm honestly quite surprised this lint doesn't just work with the naive implementation, not totally sure what's going on here!

**Comment by Milo123459** [comment]
Still not fixed... :(

**Comment by seanmonstar** [comment]
What's the behavior of it not working? I don't see any false positives in the example app, whereas I used to sometimes see it flicker.

**Comment by Milo123459** [comment]
The project it is happening on is closed source - but, whats happening is it "loses its waker" then it'll end the task somehow. If it lost the waker, how can it end the task?

**Comment by blt** [comment]
For what it's worth we see this in the [vector](https://github.com/vectordotdev/vector) project, our console being currently pinned to [sha f2c30d52c9f22de69bac38009a9183135808806c](https://github.com/vectordotdev/vector/blob/3257a32dc97f5d9f515472d520a967b8fbbe7310/Cargo.toml#L119). We'd be happy to provide any debug information, run experiments etc.

**Comment by seanmonstar** [comment]
@blt what if you update that pin to current main? There's been 2 commits since then to address this issue.

**Comment by blt** [comment]
Still happening. I've updated vector to use the most up to date SHA and have made sure my checkout of console is at the same SHA, draft-PR here: https://github.com/vectordotdev/vector/pull/9293 Screenshot: 

![Screenshot from 2021-09-21 12-44-43](https://user-images.githubusercontent.com/3579/134237347-adb8fa42-26a2-4edd-be0b-5912ddb42a5c.png)

Unfortunately I don't have a small reproduction case. My compile and run command for vector is:

``` 
> RUSTFLAGS="--cfg tokio_unstable" CARGO_PROFILE_RELEASE_DEBUG=2 cargo  build --release --no-default-features --features "tokio-console,sources-datadog,sources-syslog,sources-internal_metrics,transforms-remap,sinks-prometheus,sinks-datadog" && RUST_BACKTRACE=1 firejail --noprofile --rlimit-as=2g --cpu=1,2,3,4,5,6,7,8 ./target/release/vector -qq --config ~/projects/us/troutwine/lading/configs/vector-ddlogs-remap.toml
```

where the reference config `vector-ddlogs-remap.toml` is:

```toml
data_dir = "/tmp/data/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.datadog_agent]
type = "datadog_agent"
acknowledgements = false
address = "0.0.0.0:8282"

##
## Transforms
##

[transforms.parse_message]
type = "remap"
inputs = ["datadog_agent"]
source = '''
pyld, err = parse_json(.message)
if err == null {
  .message = pyld.mineral
}
'''

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9598"

[sinks.dd_logs_egress]
type = "datadog_logs"
inputs = ["parse_message"]
endpoint = "http://localhost:8080/v1/input"
default_api_key = "DEADBEEF"
```

I don't see waker loss when vector sits idle, only when I'm generating load. This is done with my [lading](https://github.com/blt/lading) project. I run vector against two programs from lading, `http_gen` and `http_blackhole`, run like so:

```
> cargo build --release && firejail --rlimit-as=8g --cpu=11,12 --noprofile ./target/release/http_gen --config-path configs/http_gen-dd.toml
```

```
> firejail --rlimit-as=2g  --noprofile ./target/release/http_blackhole --worker-threads 16 --concurrent-requests-max 512 --binding-addr "0.0.0.0:8080" --prometheus-addr "0.0.0.0:9002"
```

The configuration `http_gen-dd.toml` is:

```toml
worker_threads = 2
prometheus_addr = "0.0.0.0:9001"

[targets.simple]
target_uri = "http://localhost:8282/v1/input"
bytes_per_second = "500 Mb"
parallel_connections = 10
method.type = "Post"
method.variant = "DatadogLog"
method.maximum_prebuild_cache_size_bytes = "1 Gb"

[targets.simple.headers]
dd-api-key = "DEADBEEF"
```

When load is generated by `http_gen` the console reports a regular growth of waker loss. It's entirely possible it's legitimate, though some of the areas I've spot checked I'm not sure how you'd lose your waker there.
