### ISSUE TITLE
a global default trace dispatcher has already been set

### ISSUE THREAD

**Issue by mrcnski** [tokio-rs/console#505]
I instrumented an application ([polkadot](https://github.com/paritytech/polkadot-sdk)) like so:

```rs
fn main() -> eyre::Result<()> {
    console_subscriber::init();
    color_eyre::install()?;
    [...]
}
```

I built it like so:

```
RUSTFLAGS="--cfg tokio_unstable" cargo build --release
```

On running the application I get this error:

```
Error: 
   0: a global default trace dispatcher has already been set
```

**Comment by hds** [comment]
@mrcnski Thanks for your error report.

I couldn't reproduce this error with the following minimal project. Could you see if you can modify it to produce the error you see in polkadot?

`Cargo.toml`:
```toml
[package]
name = "console-eyre"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
console-subscriber = "0.2.0"
eyre = "0.6.11"
```

`src/main.rs`:
```rust
fn main() -> eyre::Result<()> {
    console_subscriber::init();
    color_eyre::install()?;

    println!("Hello, world!");

    Ok(())
}
```

I ran it with:

```sh
RUSTFLAGS="--cfg tokio_unstable" cargo run --release
```
